const DIAGRAM_KEYWORD_ALIASES: Record<string, string> = {
  ped_revenue: "ped_revenue_impact",
  ppf_balanced_growth: "ppf_growth",
  ppf_biased_growth: "ppf_growth",
  ppf_unemployment: "ppf_growth",
  ppf_inward_shift: "ppf_natural_disaster",
  max_price: "maximum_price",
  min_wage: "labour_minimum_wage",
  minimum_wage: "labour_minimum_wage",
  demand_pull_inflation: "demand_pull",
  ad_demand_pull_inflation: "demand_pull",
  supply_side_policy: "supply_side",
  ad_supply_side_policy: "supply_side",
  monetary_policy: "monetary_transmission",
  primary_product: "primary_product_dependency",
  harrod_domar: "harrod_domar_ppf",
  fiscal_ad: "fiscal_policy_ad",
  terms_trade: "terms_of_trade",
  short_run_shutdown: "shutdown_point",
  shutdown_short_run: "shutdown_point",
  monopolistic_competition_lr: "monopolistic_competition",
  monopolistic_competition_sr: "monopolistic_competition",
  perfectcomp: "perfect_competition",
  perfect_comp_lr: "perfect_competition",
  yed: "yed_luxury",
  lrac_scale: "lrac",
  economies_scale: "lrac",
  monopoly_profit: "monopoly",
  supernormal_profit: "monopoly",
  cost_push: "cost_push_inflation",
  ad_as_cost_push: "cost_push_inflation",
  ad_as: "cost_push_inflation",
  spare_capacity: "keynesian_as",
  inr_usd: "exchange_rate",
  import_quota: "tariff",
  tariff_diagram: "tariff",
  supply_demand_shifts: "ev_multiple_shifts",
  welfare_loss: "negative_externality_coal",
  sdil_welfare: "sugar_tax_sdil",
  min_avc: "shutdown_point",
  oligopoly: "kinked_demand_oligopoly",
  kinked_demand: "kinked_demand_oligopoly",
};

export function normalizeDiagramKeyword(keyword?: string | null) {
  if (!keyword) return undefined;

  const normalized = keyword.toLowerCase().trim().replace(/[\s-]+/g, "_");
  return DIAGRAM_KEYWORD_ALIASES[normalized] ?? normalized;
}