// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// URL + anon key come from the central config (env-preferred, public fallback) so a
// missing build-time env var can never white-screen the app.
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "@/lib/supabaseConfig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // PKCE is the more secure OAuth/redirect flow; detectSessionInUrl consumes the
    // session when the provider (or email/reset link) returns to the app.
    flowType: "pkce",
    detectSessionInUrl: true,
  }
});